version: "3.9"

services:
    django:
        build: ./django/
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
          - "8000:8000"
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:8000/app/profiles" ]
          interval: 15s
          timeout: 25s
        restart: unless-stopped
        depends_on:
          db:
            condition: service_healthy
        networks:
          - db
    db:
      image: postgres:14.7
      environment:
        POSTGRES_DB: ozon
        POSTGRES_USER: ozon_user
        POSTGRES_PASSWORD: 12345
      healthcheck:
        test: [ "CMD-SHELL", "echo 'SELECT 1;' | psql -U ozon_user -d ozon" ]
        interval: 3s
        timeout: 5s
      restart: unless-stopped
      ports:
        - "5432:5432"
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      networks:
        - db

networks:
    db:
        driver: bridge