version: "3.9"

services:
    db:
        image: postgres:14.7
        environment:
            POSTGRES_DB: ozon
            POSTGRES_USER: ozon_user
            POSTGRES_PASSWORD: 12345
            PGDATA: /var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "echo 'SELECT 1;' | psql -U ozon_user -d ozon" ]
            interval: 3s
            timeout: 5s
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - db
    ozon:
        build: ./project
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        networks:
            - db
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8000/app/profiles/"]
            interval: 3s
            timeout: 10s
        restart: unless-stopped
    nginx:
        image: nginx:1.21.3
        ports:
          - "8080:8080"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
          - db
        depends_on:
            ozon:
                condition: service_healthy
networks:
    db:
        driver: bridge