# Generated by Django 4.2 on 2023-05-14 15:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_character_id_alter_character_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(verbose_name='Адрес доставки')),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='characters_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hours_played',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Связанный пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile', verbose_name='Связанный продукт'),
        ),
    ]
