# Generated by Django 4.2 on 2023-05-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='destination',
            new_name='shipping_address',
        ),
    ]
