"""
Django settings for project project.

Generated by 'project-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'project-insecure-xf7gnbh1u4dic3f$b27m)h7s@4l*&37ek(by8vt)41jmzqh(dz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'project.contrib.admin',
    'project.contrib.auth',
    'project.contrib.contenttypes',
    'project.contrib.sessions',
    'project.contrib.messages',
    'project.contrib.staticfiles',
    'ozon',
    'rest_framework'
]

MIDDLEWARE = [
    'project.middleware.security.SecurityMiddleware',
    'project.contrib.sessions.middleware.SessionMiddleware',
    'project.middleware.common.CommonMiddleware',
    'project.middleware.csrf.CsrfViewMiddleware',
    'project.contrib.auth.middleware.AuthenticationMiddleware',
    'project.contrib.messages.middleware.MessageMiddleware',
    'project.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'project.db.backends.postgresql_psycopg2',
        'NAME': 'ozon',
        'USER': 'ozon_user',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'project.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'project.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'project.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'project.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'project.db.models.BigAutoField'
