version: "3.9"

services:
    service:
        build: ./project
        command: "python manage.py runserver"
        ports:
          - "8000:8000"
    nginx:
        image: nginx:1.21.3
        ports:
          - "8080:8080"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - service
    postgres:
        image: postgres:13.3
        restart: always
        environment:
            POSTGRES_DB: "ozon"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"