# Generated by Django 4.2 on 2023-05-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0003_rename_product_id_favoriteproducts_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproducts',
            options={'verbose_name': 'FavoriteProduct'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 8, 3, 907967)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 8, 3, 906969)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 8, 3, 906010)),
        ),
    ]
