# Generated by Django 4.2 on 2023-05-05 17:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0004_alter_favoriteproducts_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproducts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 28, 16, 249940), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.product', verbose_name='Связанный пользователь'),
        ),
        migrations.AlterField(
            model_name='favoriteproducts',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.profile', verbose_name='Связанный продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 28, 16, 248938), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.product', verbose_name='Связанный пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.profile', verbose_name='Связанный продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozon.profile', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 28, 16, 247939), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
