# Generated by Django 4.2 on 2023-05-05 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon', '0005_alter_favoriteproducts_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproducts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 47, 5, 951238), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 47, 5, 951238), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 47, 5, 950238), verbose_name='Дата создания'),
        ),
    ]
