# Generated by Django 4.2 on 2023-05-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Никнейм персонажа')),
                ('class_name', models.CharField(max_length=10, verbose_name='Класс')),
                ('lvl', models.IntegerField(verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('rarity', models.CharField(max_length=50, verbose_name='Редкость')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('hours_played', models.IntegerField(verbose_name='Количество часов сыграно')),
                ('characters_count', models.IntegerField(verbose_name='Количество персонажей')),
                ('characters', models.ManyToManyField(to='app.character', verbose_name='Персонажи')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.item', verbose_name='Инвентарь'),
        ),
    ]
