# Generated by Django 4.2 on 2023-05-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_product_remove_profile_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
